// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GlasAnketa.DataAccess.Migrations
{
    public partial class AllowMultipleAnswersPerUserQuestion : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_Answers_UserId_QuestionId_QuestionFormId",
                table: "Answers");

            migrationBuilder.CreateIndex(
                name: "IX_Answers_UserId_QuestionId_QuestionFormId",
                table: "Answers",
                columns: new[] { "UserId", "QuestionId", "QuestionFormId" });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_Answers_UserId_QuestionId_QuestionFormId",
                table: "Answers");

            migrationBuilder.CreateIndex(
                name: "IX_Answers_UserId_QuestionId_QuestionFormId",
                table: "Answers",
                columns: new[] { "UserId", "QuestionId", "QuestionFormId" },
                unique: true);
        }
    }
}
